name: 'Check up-to-date with WP'
description: 'Check if the plugin or theme is up-to-date with the latest WordPress'
inputs:
  readme:
    description: 'Readme file to where "Tested up to" is written.'
    required: false
    default: 'README.md'
outputs:
  should_update:
    description: 'Should update WordPress or not.'
  version:
    description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: 'blue'
  icon: 'refresh-cw'
